# CHTC maintained container for AlphaFold3 as of December 2025
# Can use the local CHTC copy at file:///staging/groups/chtc_staff/containers/alphafold3.minimal.22Jan2025.sif
container_image = osdf:///osg-public/containers/alphafold3.minimal.22Jan2025.sif

executable = inference_pipeline.sh

environment = "myjobdir=$(my_directory)"

MODEL_WEIGHTS_PATH = /staging/<NetID>/tutorial-CHTC-AF3/af3.bin.zst

log = ./logs/inference_pipeline.log
output = inference_pipeline_$(Cluster)_$(Process).out
error  = inference_pipeline_$(Cluster)_$(Process).err

initialdir = $(my_directory)

# transfer all files in the inference_inputs directory
transfer_input_files = inference_inputs/, osdf:///chtc/$(MODEL_WEIGHTS_PATH)

should_transfer_files = YES
when_to_transfer_output = ON_EXIT

request_memory = 8GB
# need space for the container (3GB) as well
request_disk = 10GB
request_cpus = 4
request_gpus = 1

# Use the CHTC recommended AF3 memory requirement based on the number of tokens
gpus_minimum_memory = 15 GB

# short jobs 4-6 hours so it is okay to use is_resumable
+GPUJobLength = "short"
+WantGPULab = true
+is_resumable = true
+want_ospool = true

# Use --user-specified-alphafold-options to pass any extra options to AlphaFold3, such as
# arguments = --model_param_file af3.bin.zst --work_dir_ext $(Cluster)_$(Process) --user-specified-alphafold-options "--buckets 5982"
arguments = --model_param_file af3.bin.zst --work_dir_ext $(Cluster)_$(Process)

queue my_directory from list_of_af3_jobs.txt
